### ISSUE TITLE
Implicit declaration of function errors while running make.

### ISSUE THREAD

**Issue by burdorfm** [N-BodyShop/tipsy#8]
Hi,

I was trying to install tipsy using the code repository here. I have a macOS Catalina 10.15.7. Initially I was getting errors identical to tipsy install issue #7, but I think I fixed that by installing and linking XQuartz. I downloaded the repository with:

```
gh repo clone N-BodyShop/tipsy
```

Then I navigated to the code directory and ran:

```
./configure
```

After that ran, I ran make.  I get the following errors:

```
gcc -c  -I. -I. -g -O2 -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STRING_H=1 -DX_DISPLAY_MISSING=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1  ascii2binary.c
ascii2binary.c:57:28: error: implicit declaration of function 'free' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        if(gas_particles != NULL) free(gas_particles);
                                  ^
1 error generated.
make: *** [ascii2binary.o] Error 1
```

If I add the line:

```
#include <stdlib.h>
```

to the file defs.h then the error becomes:

```
.
.
.
gcc -c  -I. -I. -g -O2 -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STRING_H=1 -DX_DISPLAY_MISSING=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1  ell_distance.c
ell_distance.c:14:5: error: implicit declaration of function 'matrix_vector_mult' is invalid in
      C99 [-Werror,-Wimplicit-function-declaration]
    matrix_vector_mult(ell_matrix,dx,dx_rot) ;
    ^
```

In this case I have only posted the last part of the output. I looked at the file ascii2binary.c and there is a comment:

 * Revision 2.4  1993/04/05  11:06:11  trq
 * Deleted declaration of free() - conflicts with some OS headers.

I spent quite a few hours trying to read up on makefile and understand why certain functions weren't being directly declared in the header files (or they were declared but the header file containing them wasn't included in the specific c file). Any help on how to resolve this issue would be amazing.

**Comment by trquinn** [comment]
Note the date on that comment: the code was written when implicit declarations were commonly used.   A quick work-around is to add -Wno-error to the CFLAGS macro in the Makefile, which should turn these back into warnings.  A better fix is to have an "#include "fdefs.h"" at the top of ell_distance.c

**Comment by burdorfm** [comment]
Ty for the help! I tried to implement the quick work-around, but I'm still getting the same errors. Is this what you meant by adding to the CFLAGS macro:

I changed 

```
CFLAGS = -g -O2 $(DEFS) $(X_CFLAGS)
```

to

```
CFLAGS = -g -O2 -Wno-error $(DEFS) $(X_CFLAGS)
```

in Makefile after executing configure. Also, I spent quite a few hours trying to implement the better fix with no success. When I included fdefs.h in ell_distance.c, another implicit function error cropped  up in another file and so on. Many of these implicit function errors did not seem to be fixed by including relevant header files.

**Comment by trquinn** [comment]
Try out pull request #9 to see if it fixes things.

**Comment by burdorfm** [comment]
I tried out the pull request and it seems to almost work for me. I first removed and recloned tipsy, then i navigated to the tipsy directory and ran:
```
gh pr checkout 9
```
which seemed to get the pull request.

I then executed the configure and attempted to run the makefile, which errored out with:
```
framepoints.c:3:1: warning: type specifier missing, defaults to 'int'
      [-Wimplicit-int]
framepoints(job)
^
framepoints.c:28:6: error: non-void function 'framepoints' should return a value
      [-Wreturn-type]
            return ;
```

I added void as the type specifier and ran make again (I also uninstalled and reinstalled before making the edits). I then got similar errors for the files moments.c, arraymoments.c, rotate_sub.c, markstat.c, and packfit.c. The file sortarray.c gave the return type error for the opposite reason (a function with an integer return type returning nothing). To fix the error 
 for sortarray.c I changed line 72 to return -1.

Running make after these edits is where I hit a wall. The file readline.c gives me 87 warnings and 2 errors. The errors are:

```
readline.c:1013:3: error: implicit declaration of function 'rl_set_keymap_from_edit_mode' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  rl_set_keymap_from_edit_mode ();
  ^
readline.c:1030:3: error: implicit declaration of function 'rltty_set_default_bindings' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  rltty_set_default_bindings (_rl_keymap);
```

I spent a couple hours trying to get it to run - with attempts ranging from commenting out the relevant lines to including other files to copying and pasting function definitions into readline, and have so far been unsuccessful.

**Comment by trquinn** [comment]
I fixed a bunch of implicit declarations.  Try pulling the pull request again.

**Comment by burdorfm** [comment]
I downloaded the updated pull request, and it worked quite well. The only errors that were thrown were in the readline folder for rltty.c:

```
gcc -c -DHAVE_CONFIG_H -I. -I. -g rltty.c
rltty.c:383:7: error: implicit declaration of function 'ioctl' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  if (ioctl (tty, TIOCGWINSZ, &w) == 0)
      ^
rltty.c:584:3: error: implicit declaration of function 'ioctl' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  ioctl (fildes, TIOCSTART, 0);
  ^
rltty.c:618:3: error: implicit declaration of function 'ioctl' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  ioctl (fildes, TIOCSTOP, 0);
```
I added  
```
#include <sys/ioctl.h>  
```
to the top of the file and that seemed to fix those errors. Then, after fixing a linker error because I failed to add certain libraries to my path, the tipsy executable was successfully created. I was able to load the sample file and the changa testcosmo cube300 output. Thank you for your help in this process I would not have been able to install tipsy without it!
